version: '3.4'

services:
  ludustack-db:
      image: mongo:latest
      hostname: mongodb
      ports:
        - '27017:27017'
      environment:
        - MONGO_REPLICA_SET_NAME=dan
      command:
        - --storageEngine
        - wiredTiger
        - --replSet
        - myrepl
      healthcheck:
        test: test $$(echo "rs.initiate().ok || rs.status().ok" --quiet) -eq 1
        interval: 60s
        start_period: 60s