version: '3.3'

services:
    web-random:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-random-image
        ports:
            - "800:5000"
        entrypoint: python /root/flask-mongodb-example/python/random_demo.py
        deploy:
          restart_policy:
            condition: on-failure
        depends_on:
            - mongo

    web-users:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-users-image
        ports:
            - "81:5000"
        entrypoint: python /root/flask-mongodb-example/python/users.py
        deploy:
          restart_policy:
            condition: on-failure
        depends_on:
            - mongo

    web-mqtt:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-mqtt.txt
        image: web-mqtt-image
        entrypoint: python /root/flask-mongodb-example/python/mqtt.py
        deploy:
          restart_policy:
            condition: on-failure
        environment:
             - PYTHONUNBUFFERED=1
        depends_on:
            - mongo
            - mqtt
            - influxdb
        tty: true

    web-fulltext-search:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-fulltext-image
        ports:
            - "82:5000"
        entrypoint: python /root/flask-mongodb-example/python/fulltext_search.py
        deploy:
          restart_policy:
            condition: on-failure
        depends_on:
            - mongo

    web-geolocation-search:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-geolocation-image
        ports:
            - "83:5000"
        entrypoint: python /root/flask-mongodb-example/python/geolocation_search.py
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mongo

    web-baesian:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-baesian-image
        ports:
            - "84:5000"
        entrypoint: python /root/flask-mongodb-example/python/baesian.py
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mongo

    web-photo-process:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-photo.txt
        image: web-photo-image
        ports:
            - "85:5000"
        entrypoint: python /root/flask-mongodb-example/python/photo_process.py
        volumes:
            - ./container-storage:/root/storage
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mongo

    web-book-collection:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-restplus.txt
        image: web-bookcollection-image
        environment:
             - PYTHONUNBUFFERED=1
        ports:
            - "86:5000"
        entrypoint: python /root/flask-mongodb-example/python/bookcollection.py
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mongo
            - web-users

    web-users-fast-api:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-fastapi.txt
        image: web-users-fastapi-image
        ports:
            - "88:5000" # port 87 is restricted in browsers
        entrypoint: uvicorn users-fastapi:app --reload --host 0.0.0.0 --port 5000
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mongo

    influxdb:
        build: docker-influxdb
        env_file: configuration.env
        ports:
          - '8086:8086'
        volumes:
          - influxdb_data:/var/lib/influxdb

    grafana:
        build: docker-grafana
        env_file: configuration.env
        links:
          - influxdb
        ports:
          - '3000:3000'
        volumes:
          - grafana_data:/var/lib/grafana

    mongo:
        image: mongo:4.2-bionic
        deploy:
            restart_policy:
                condition: always
        command:
        - --storageEngine
        - wiredTiger
        - --replSet
        - myrepl
        ports:
            - "27017:27017"

    mqtt:
        build:
          context: ./docker-mosquitto
        deploy:
            restart_policy:
                condition: always
        ports:
            - "1883:1883"

    krakend:
        image: devopsfaith/krakend
        volumes:
            - ./:/etc/krakend/
        configs:
          - krakend_config
        ports:
            - "8080:8080"

volumes:
    grafana_data: {}
    influxdb_data: {}

configs:
  krakend_config:
    file: ./krakend.json