name: nexite-build
on:
  push:
    branches:
      - 'test-**' 
  pull_request:
    branches:
      - 'test-**'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build  python
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nexite/Dockerfile
          push: true
          tags: alllomancer/python:${{ steps.extract_branch.outputs.branch }}






